version: 2.1

jobs:
  test:
    parameters:
      version:
        type: string
      commands:
        type: string
    docker:
      - image: cimg/elixir:<< parameters.version >>
    steps:
      - checkout
      - run: rm -rf _build; make << parameters.commands >>

workflows:
  version: 2
  general:
    jobs:
      - test:
          name: "test-26"
          version: "1.15.7-erlang-26.0.2"
          commands: "ci edoc"
      - test:
          name: "test-25"
          version: "1.15.7-erlang-25.3.2"
          commands: "ci edoc"
      - test:
          name: "test-24"
          version: "1.15.7-erlang-24.3.4"
          commands: "ci edoc"
